# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ayush/Desktop/Stuff/flockSim

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ayush/Desktop/Stuff/flockSim

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ayush/Desktop/Stuff/flockSim/CMakeFiles /home/ayush/Desktop/Stuff/flockSim//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ayush/Desktop/Stuff/flockSim/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named flockSim

# Build rule for target.
flockSim: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 flockSim
.PHONY : flockSim

# fast build rule for target.
flockSim/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flockSim.dir/build.make CMakeFiles/flockSim.dir/build
.PHONY : flockSim/fast

src/Bird.o: src/Bird.cpp.o
.PHONY : src/Bird.o

# target to build an object file
src/Bird.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flockSim.dir/build.make CMakeFiles/flockSim.dir/src/Bird.cpp.o
.PHONY : src/Bird.cpp.o

src/Bird.i: src/Bird.cpp.i
.PHONY : src/Bird.i

# target to preprocess a source file
src/Bird.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flockSim.dir/build.make CMakeFiles/flockSim.dir/src/Bird.cpp.i
.PHONY : src/Bird.cpp.i

src/Bird.s: src/Bird.cpp.s
.PHONY : src/Bird.s

# target to generate assembly for a file
src/Bird.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flockSim.dir/build.make CMakeFiles/flockSim.dir/src/Bird.cpp.s
.PHONY : src/Bird.cpp.s

src/Flock.o: src/Flock.cpp.o
.PHONY : src/Flock.o

# target to build an object file
src/Flock.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flockSim.dir/build.make CMakeFiles/flockSim.dir/src/Flock.cpp.o
.PHONY : src/Flock.cpp.o

src/Flock.i: src/Flock.cpp.i
.PHONY : src/Flock.i

# target to preprocess a source file
src/Flock.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flockSim.dir/build.make CMakeFiles/flockSim.dir/src/Flock.cpp.i
.PHONY : src/Flock.cpp.i

src/Flock.s: src/Flock.cpp.s
.PHONY : src/Flock.s

# target to generate assembly for a file
src/Flock.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flockSim.dir/build.make CMakeFiles/flockSim.dir/src/Flock.cpp.s
.PHONY : src/Flock.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flockSim.dir/build.make CMakeFiles/flockSim.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flockSim.dir/build.make CMakeFiles/flockSim.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flockSim.dir/build.make CMakeFiles/flockSim.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... flockSim"
	@echo "... src/Bird.o"
	@echo "... src/Bird.i"
	@echo "... src/Bird.s"
	@echo "... src/Flock.o"
	@echo "... src/Flock.i"
	@echo "... src/Flock.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

